---
before_install:
  - sudo apt-getupdate

install:
  - sudo apt-get install hugo
  - sudo apt-get install nodejs
  - npm i -g autoprefixer postcss-cli

script:
  - hugo version
  - hugo

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master